/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package spec.model;

/**
 * Status of a game server.
 *
 * @see <a href="https://schema.org/GameServerStatus">https://schema.org/GameServerStatus</a>
 */
public interface GameServerStatus extends StatusEnumeration {
}
