/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package spec.model;

/**
 * A particular online business, either standalone or the online part of a broader organization. Examples include an eCommerce site, an online travel booking site, an online learning site, an online logistics and shipping provider, an online (virtual) doctor, etc.
 *
 * @see <a href="https://pending.schema.org">https://pending.schema.org</a>
 * @see <a href="https://github.com/schemaorg/schemaorg/issues/3028">https://github.com/schemaorg/schemaorg/issues/3028</a>
 * @see <a href="https://schema.org/OnlineBusiness">https://schema.org/OnlineBusiness</a>
 */
public interface OnlineBusiness extends Organization {
}
