/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package spec.model;

/**
 * Enumerates different price types, for example list price, invoice price, and sale price.
 *
 * @see <a href="https://pending.schema.org">https://pending.schema.org</a>
 * @see <a href="https://github.com/schemaorg/schemaorg/issues/2712">https://github.com/schemaorg/schemaorg/issues/2712</a>
 * @see <a href="https://schema.org/PriceTypeEnumeration">https://schema.org/PriceTypeEnumeration</a>
 */
public interface PriceTypeEnumeration extends Enumeration {
}
