/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package spec.model;

import java.util.List;
import spec.model.TVSeries;

/**
 * A short TV program or a segment/part of a TV program.
 *
 * @see <a href="https://schema.org/TVClip">https://schema.org/TVClip</a>
 */
public interface TVClip extends Clip {

    /**
     * The TV series to which this episode or season belongs.
     *
     * @return {@link TVSeries}
     */
    List<TVSeries> getPartOfTVSeriesList();

    /**
     * The TV series to which this episode or season belongs.
     *
     * @return {@link TVSeries}
     */
    TVSeries getPartOfTVSeries();

    /**
     * The TV series to which this episode or season belongs.
     *
     * @param partOfTVSeries TVSeries value to set.
     */
    void addPartOfTVSeries(TVSeries partOfTVSeries);
}
