/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package spec_custom.model;

import java.util.List;

/**
 * Enumeration(s) for use with [[measurementMethod]].
 *
 * @see <a href="https://pending.schema.org">https://pending.schema.org</a>
 * @see <a href="https://github.com/schemaorg/schemaorg/issues/2564">https://github.com/schemaorg/schemaorg/issues/2564</a>
 * @see <a href="https://schema.org/MeasurementMethodEnum">https://schema.org/MeasurementMethodEnum</a>
 */
public interface MeasurementMethodEnum extends Enumeration {
}
