/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package spec_custom.model;

import java.util.List;

/**
 * Enumerates several kinds of product return refund types.
 *
 * @see <a href="https://pending.schema.org">https://pending.schema.org</a>
 * @see <a href="https://github.com/schemaorg/schemaorg/issues/2288">https://github.com/schemaorg/schemaorg/issues/2288</a>
 * @see <a href="https://schema.org/RefundTypeEnumeration">https://schema.org/RefundTypeEnumeration</a>
 */
public interface RefundTypeEnumeration extends Enumeration {
}
