/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package spec_custom.model;

import java.util.List;
import spec_custom.model.Thing;

/**
 * The act of editing a recipient by replacing an old object with a new object.
 *
 * @see <a href="https://schema.org/ReplaceAction">https://schema.org/ReplaceAction</a>
 */
public interface ReplaceAction extends UpdateAction {

    /**
     * A sub property of object. The object that is being replaced.
     *
     * @return {@link Thing}
     */
    List<Thing> getReplaceeList();

    /**
     * A sub property of object. The object that is being replaced.
     *
     * @return {@link Thing}
     */
    Thing getReplacee();

    /**
     * A sub property of object. The object that is being replaced.
     *
     * @param replacee Thing value to set.
     */
    void addReplacee(Thing replacee);

    /**
     * A sub property of object. The object that replaces.
     *
     * @return {@link Thing}
     */
    List<Thing> getReplacerList();

    /**
     * A sub property of object. The object that replaces.
     *
     * @return {@link Thing}
     */
    Thing getReplacer();

    /**
     * A sub property of object. The object that replaces.
     *
     * @param replacer Thing value to set.
     */
    void addReplacer(Thing replacer);
}
