/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package org.schema.model;

import org.schema.model.datatype.Text;

/**
 * Reference documentation for application programming interfaces (APIs).
 *
 * @see <a href="https://schema.org/APIReference">https://schema.org/APIReference</a>
 */
public interface APIReference extends TechArticle {

    /**
     * Library file name e.g., mscorlib.dll, system.web.dll.
     *
     * @return {@link Text}
     */
    Text getAssembly();

    /**
     * Library file name e.g., mscorlib.dll, system.web.dll.
     *
     * @param fAssembly Text value to set.
     */
    void setAssembly(Text fAssembly);
    /**
     * Library file name e.g., mscorlib.dll, system.web.dll.
     *
     * @param fAssembly java.lang.String value to set.
     */
    void setAssembly(java.lang.String fAssembly);

    /**
     * Type of app development: phone, Metro style, desktop, XBox, etc.
     *
     * @return {@link Text}
     */
    Text getTargetPlatform();

    /**
     * Type of app development: phone, Metro style, desktop, XBox, etc.
     *
     * @param fTargetPlatform Text value to set.
     */
    void setTargetPlatform(Text fTargetPlatform);
    /**
     * Type of app development: phone, Metro style, desktop, XBox, etc.
     *
     * @param fTargetPlatform java.lang.String value to set.
     */
    void setTargetPlatform(java.lang.String fTargetPlatform);

    /**
     * Library file name e.g., mscorlib.dll, system.web.dll.
     *
     * @return {@link Text}
     */
    Text getExecutableLibraryName();

    /**
     * Library file name e.g., mscorlib.dll, system.web.dll.
     *
     * @param fExecutableLibraryName Text value to set.
     */
    void setExecutableLibraryName(Text fExecutableLibraryName);
    /**
     * Library file name e.g., mscorlib.dll, system.web.dll.
     *
     * @param fExecutableLibraryName java.lang.String value to set.
     */
    void setExecutableLibraryName(java.lang.String fExecutableLibraryName);

    /**
     * Indicates whether API is managed or unmanaged.
     *
     * @return {@link Text}
     */
    Text getProgrammingModel();

    /**
     * Indicates whether API is managed or unmanaged.
     *
     * @param fProgrammingModel Text value to set.
     */
    void setProgrammingModel(Text fProgrammingModel);
    /**
     * Indicates whether API is managed or unmanaged.
     *
     * @param fProgrammingModel java.lang.String value to set.
     */
    void setProgrammingModel(java.lang.String fProgrammingModel);

    /**
     * Associated product/technology version. e.g., .NET Framework 4.5.
     *
     * @return {@link Text}
     */
    Text getAssemblyVersion();

    /**
     * Associated product/technology version. e.g., .NET Framework 4.5.
     *
     * @param fAssemblyVersion Text value to set.
     */
    void setAssemblyVersion(Text fAssemblyVersion);
    /**
     * Associated product/technology version. e.g., .NET Framework 4.5.
     *
     * @param fAssemblyVersion java.lang.String value to set.
     */
    void setAssemblyVersion(java.lang.String fAssemblyVersion);
}
