/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package org.schema.model;

import java.util.List;

/**
 * An agent inspects, determines, investigates, inquires, or examines an object's accuracy, quality, condition, or state.
 *
 * @see <a href="https://schema.org/CheckAction">https://schema.org/CheckAction</a>
 */
public interface CheckAction extends FindAction {
}
