/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package org.schema.model;

import java.util.List;

/**
 * A page devoted to a single item, such as a particular product or hotel.
 *
 * @see <a href="https://schema.org/ItemPage">https://schema.org/ItemPage</a>
 */
public interface ItemPage extends WebPage {
}
