/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package org.schema.model;

import org.schema.model.Person;
import org.schema.model.ContactPoint;
import org.schema.model.Organization;
import org.schema.model.Audience;
import org.schema.model.datatype.DateTime;
import org.schema.model.CreativeWork;
import org.schema.model.datatype.Date;

/**
 * A single message from a sender to one or more organizations or people.
 *
 * @see <a href="https://schema.org/Message">https://schema.org/Message</a>
 */
public interface Message extends CreativeWork {

    /**
     * A sub property of recipient. The recipient blind copied on a message.
     *
     * @return {@link Person} or {@link ContactPoint} or {@link Organization}
     */
    <T> T getBccRecipient();

    /**
     * A sub property of recipient. The recipient blind copied on a message.
     *
     * @param bccRecipient Person value to set.
     */
    void setBccRecipient(Person bccRecipient);
    /**
     * A sub property of recipient. The recipient blind copied on a message.
     *
     * @param bccRecipient ContactPoint value to set.
     */
    void setBccRecipient(ContactPoint bccRecipient);
    /**
     * A sub property of recipient. The recipient blind copied on a message.
     *
     * @param bccRecipient Organization value to set.
     */
    void setBccRecipient(Organization bccRecipient);

    /**
     * A sub property of participant. The participant who is at the receiving end of the action.
     *
     * @return {@link Person} or {@link Audience} or {@link ContactPoint} or {@link Organization}
     */
    <T> T getRecipient();

    /**
     * A sub property of participant. The participant who is at the receiving end of the action.
     *
     * @param recipient Person value to set.
     */
    void setRecipient(Person recipient);
    /**
     * A sub property of participant. The participant who is at the receiving end of the action.
     *
     * @param recipient Audience value to set.
     */
    void setRecipient(Audience recipient);
    /**
     * A sub property of participant. The participant who is at the receiving end of the action.
     *
     * @param recipient ContactPoint value to set.
     */
    void setRecipient(ContactPoint recipient);
    /**
     * A sub property of participant. The participant who is at the receiving end of the action.
     *
     * @param recipient Organization value to set.
     */
    void setRecipient(Organization recipient);

    /**
     * The date/time the message was received if a single recipient exists.
     *
     * @return {@link DateTime}
     */
    DateTime getDateReceived();

    /**
     * The date/time the message was received if a single recipient exists.
     *
     * @param dateReceived DateTime value to set.
     */
    void setDateReceived(DateTime dateReceived);

    /**
     * A sub property of recipient. The recipient copied on a message.
     *
     * @return {@link Person} or {@link Organization} or {@link ContactPoint}
     */
    <T> T getCcRecipient();

    /**
     * A sub property of recipient. The recipient copied on a message.
     *
     * @param ccRecipient Person value to set.
     */
    void setCcRecipient(Person ccRecipient);
    /**
     * A sub property of recipient. The recipient copied on a message.
     *
     * @param ccRecipient Organization value to set.
     */
    void setCcRecipient(Organization ccRecipient);
    /**
     * A sub property of recipient. The recipient copied on a message.
     *
     * @param ccRecipient ContactPoint value to set.
     */
    void setCcRecipient(ContactPoint ccRecipient);

    /**
     * A CreativeWork attached to the message.
     *
     * @return {@link CreativeWork}
     */
    CreativeWork getMessageAttachment();

    /**
     * A CreativeWork attached to the message.
     *
     * @param messageAttachment CreativeWork value to set.
     */
    void setMessageAttachment(CreativeWork messageAttachment);

    /**
     * A sub property of recipient. The recipient who was directly sent the message.
     *
     * @return {@link ContactPoint} or {@link Person} or {@link Audience} or {@link Organization}
     */
    <T> T getToRecipient();

    /**
     * A sub property of recipient. The recipient who was directly sent the message.
     *
     * @param toRecipient ContactPoint value to set.
     */
    void setToRecipient(ContactPoint toRecipient);
    /**
     * A sub property of recipient. The recipient who was directly sent the message.
     *
     * @param toRecipient Person value to set.
     */
    void setToRecipient(Person toRecipient);
    /**
     * A sub property of recipient. The recipient who was directly sent the message.
     *
     * @param toRecipient Audience value to set.
     */
    void setToRecipient(Audience toRecipient);
    /**
     * A sub property of recipient. The recipient who was directly sent the message.
     *
     * @param toRecipient Organization value to set.
     */
    void setToRecipient(Organization toRecipient);

    /**
     * The date/time at which the message was sent.
     *
     * @return {@link DateTime}
     */
    DateTime getDateSent();

    /**
     * The date/time at which the message was sent.
     *
     * @param dateSent DateTime value to set.
     */
    void setDateSent(DateTime dateSent);

    /**
     * The date/time at which the message has been read by the recipient if a single recipient exists.
     *
     * @return {@link Date} or {@link DateTime}
     */
    <T> T getDateRead();

    /**
     * The date/time at which the message has been read by the recipient if a single recipient exists.
     *
     * @param dateRead Date value to set.
     */
    void setDateRead(Date dateRead);
    /**
     * The date/time at which the message has been read by the recipient if a single recipient exists.
     *
     * @param dateRead DateTime value to set.
     */
    void setDateRead(DateTime dateRead);

    /**
     * A sub property of participant. The participant who is at the sending end of the action.
     *
     * @return {@link Person} or {@link Audience} or {@link Organization}
     */
    <T> T getSender();

    /**
     * A sub property of participant. The participant who is at the sending end of the action.
     *
     * @param sender Person value to set.
     */
    void setSender(Person sender);
    /**
     * A sub property of participant. The participant who is at the sending end of the action.
     *
     * @param sender Audience value to set.
     */
    void setSender(Audience sender);
    /**
     * A sub property of participant. The participant who is at the sending end of the action.
     *
     * @param sender Organization value to set.
     */
    void setSender(Organization sender);
}
