/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package org.schema.model;

import java.util.List;

/**
 * Categories of physical activity, organized by physiologic classification.
 *
 * @see <a href="https://health-lifesci.schema.org">https://health-lifesci.schema.org</a>
 * @see <a href="https://schema.org/PhysicalActivityCategory">https://schema.org/PhysicalActivityCategory</a>
 */
public interface PhysicalActivityCategory extends Enumeration {
}
