/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package org.schema.model;


/**
 * The act of resuming a device or application which was formerly paused (e.g. resume music playback or resume a timer).
 *
 * @see <a href="https://schema.org/ResumeAction">https://schema.org/ResumeAction</a>
 */
public interface ResumeAction extends ControlAction {
}
