/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package org.schema.model;


/**
 * A place offering space for "Recreational Vehicles", Caravans, mobile homes and the like.
 *
 * @see <a href="https://schema.org/RVPark">https://schema.org/RVPark</a>
 */
public interface RVPark extends CivicStructure {
}
