/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package org.schema.model;


/**
 * A value indicating a steering position.
 *
 * @see <a href="http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#Automotive_Ontology_Working_Group">http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#Automotive_Ontology_Working_Group</a>
 * @see <a href="https://schema.org/SteeringPositionValue">https://schema.org/SteeringPositionValue</a>
 */
public interface SteeringPositionValue extends QualitativeValue {
}
