/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package org.schema.model;

import java.util.List;

/**
 * A table on a Web page.
 *
 * @see <a href="https://schema.org/Table">https://schema.org/Table</a>
 */
public interface Table extends WebPageElement {
}
