/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package spec_custom.model.impl;

import com.weedow.schemaorg.commons.model.JsonLdFieldTypes;
import com.weedow.schemaorg.commons.model.JsonLdTypeName;
import java.util.List;
import spec_custom.model.Action;
import spec_custom.model.AdministrativeArea;
import spec_custom.model.AggregateRating;
import spec_custom.model.Audience;
import spec_custom.model.Brand;
import spec_custom.model.CableOrSatelliteService;
import spec_custom.model.CategoryCode;
import spec_custom.model.Certification;
import spec_custom.model.CreativeWork;
import spec_custom.model.Demand;
import spec_custom.model.Event;
import spec_custom.model.GeoShape;
import spec_custom.model.GovernmentBenefitsType;
import spec_custom.model.ImageObject;
import spec_custom.model.Intangible;
import spec_custom.model.Offer;
import spec_custom.model.OfferCatalog;
import spec_custom.model.OpeningHoursSpecification;
import spec_custom.model.Organization;
import spec_custom.model.Person;
import spec_custom.model.PhysicalActivityCategory;
import spec_custom.model.Place;
import spec_custom.model.Product;
import spec_custom.model.PropertyValue;
import spec_custom.model.Review;
import spec_custom.model.Service;
import spec_custom.model.ServiceChannel;
import spec_custom.model.TextObject;
import spec_custom.model.Thing;
import spec_custom.model.datatype.Text;
import spec_custom.model.datatype.URL;

/**
 * A service which provides access to media programming like TV or radio. Access may be via cable or satellite.
 *
 * @see <a href="https://schema.org/CableOrSatelliteService">https://schema.org/CableOrSatelliteService</a>
 */
@JsonLdTypeName("CableOrSatelliteService")
public class CableOrSatelliteServiceImpl extends com.weedow.schemaorg.commons.model.JsonLdNodeImpl implements CableOrSatelliteService {

    @JsonLdFieldTypes({ URL.class, Text.class })
    private List<Object> additionalType;

    @Override
    public <T> List<T> getAdditionalTypeList() {
        return (List<T>) additionalType;
    }

    @Override
    public <T> T getAdditionalType() {
        return (T) getFirst(additionalType);
    }

    @Override
    public void addAdditionalType(URL additionalType) {
        this.additionalType = add(this.additionalType, additionalType);
    }
    @Override
    public void addAdditionalType(Text additionalType) {
        this.additionalType = add(this.additionalType, additionalType);
    }

    private List<AggregateRating> aggregateRating;

    @Override
    public List<AggregateRating> getAggregateRatingList() {
        return aggregateRating;
    }

    @Override
    public AggregateRating getAggregateRating() {
        return getFirst(aggregateRating);
    }

    @Override
    public void addAggregateRating(AggregateRating aggregateRating) {
        this.aggregateRating = add(this.aggregateRating, aggregateRating);
    }

    private List<Text> alternateName;

    @Override
    public List<Text> getAlternateNameList() {
        return alternateName;
    }

    @Override
    public Text getAlternateName() {
        return getFirst(alternateName);
    }

    @Override
    public void addAlternateName(Text alternateName) {
        this.alternateName = add(this.alternateName, alternateName);
    }

    @JsonLdFieldTypes({ Place.class, AdministrativeArea.class, GeoShape.class, Text.class })
    private List<Object> areaServed;

    @Override
    public <T> List<T> getAreaServedList() {
        return (List<T>) areaServed;
    }

    @Override
    public <T> T getAreaServed() {
        return (T) getFirst(areaServed);
    }

    @Override
    public void addAreaServed(Place areaServed) {
        this.areaServed = add(this.areaServed, areaServed);
    }
    @Override
    public void addAreaServed(AdministrativeArea areaServed) {
        this.areaServed = add(this.areaServed, areaServed);
    }
    @Override
    public void addAreaServed(GeoShape areaServed) {
        this.areaServed = add(this.areaServed, areaServed);
    }
    @Override
    public void addAreaServed(Text areaServed) {
        this.areaServed = add(this.areaServed, areaServed);
    }

    private List<Audience> audience;

    @Override
    public List<Audience> getAudienceList() {
        return audience;
    }

    @Override
    public Audience getAudience() {
        return getFirst(audience);
    }

    @Override
    public void addAudience(Audience audience) {
        this.audience = add(this.audience, audience);
    }

    private List<ServiceChannel> availableChannel;

    @Override
    public List<ServiceChannel> getAvailableChannelList() {
        return availableChannel;
    }

    @Override
    public ServiceChannel getAvailableChannel() {
        return getFirst(availableChannel);
    }

    @Override
    public void addAvailableChannel(ServiceChannel availableChannel) {
        this.availableChannel = add(this.availableChannel, availableChannel);
    }

    private List<Text> award;

    @Override
    public List<Text> getAwardList() {
        return award;
    }

    @Override
    public Text getAward() {
        return getFirst(award);
    }

    @Override
    public void addAward(Text award) {
        this.award = add(this.award, award);
    }

    @JsonLdFieldTypes({ Brand.class, Organization.class })
    private List<Object> brand;

    @Override
    public <T> List<T> getBrandList() {
        return (List<T>) brand;
    }

    @Override
    public <T> T getBrand() {
        return (T) getFirst(brand);
    }

    @Override
    public void addBrand(Brand brand) {
        this.brand = add(this.brand, brand);
    }
    @Override
    public void addBrand(Organization brand) {
        this.brand = add(this.brand, brand);
    }

    @JsonLdFieldTypes({ Person.class, Organization.class })
    private List<Object> broker;

    @Override
    public <T> List<T> getBrokerList() {
        return (List<T>) broker;
    }

    @Override
    public <T> T getBroker() {
        return (T) getFirst(broker);
    }

    @Override
    public void addBroker(Person broker) {
        this.broker = add(this.broker, broker);
    }
    @Override
    public void addBroker(Organization broker) {
        this.broker = add(this.broker, broker);
    }

    @JsonLdFieldTypes({ Text.class, PhysicalActivityCategory.class, CategoryCode.class, Thing.class, URL.class })
    private List<Object> category;

    @Override
    public <T> List<T> getCategoryList() {
        return (List<T>) category;
    }

    @Override
    public <T> T getCategory() {
        return (T) getFirst(category);
    }

    @Override
    public void addCategory(Text category) {
        this.category = add(this.category, category);
    }
    @Override
    public void addCategory(PhysicalActivityCategory category) {
        this.category = add(this.category, category);
    }
    @Override
    public void addCategory(CategoryCode category) {
        this.category = add(this.category, category);
    }
    @Override
    public void addCategory(Thing category) {
        this.category = add(this.category, category);
    }
    @Override
    public void addCategory(URL category) {
        this.category = add(this.category, category);
    }

    @JsonLdFieldTypes({ TextObject.class, Text.class })
    private List<Object> description;

    @Override
    public <T> List<T> getDescriptionList() {
        return (List<T>) description;
    }

    @Override
    public <T> T getDescription() {
        return (T) getFirst(description);
    }

    @Override
    public void addDescription(TextObject description) {
        this.description = add(this.description, description);
    }
    @Override
    public void addDescription(Text description) {
        this.description = add(this.description, description);
    }

    private List<Text> disambiguatingDescription;

    @Override
    public List<Text> getDisambiguatingDescriptionList() {
        return disambiguatingDescription;
    }

    @Override
    public Text getDisambiguatingDescription() {
        return getFirst(disambiguatingDescription);
    }

    @Override
    public void addDisambiguatingDescription(Text disambiguatingDescription) {
        this.disambiguatingDescription = add(this.disambiguatingDescription, disambiguatingDescription);
    }

    private List<Certification> hasCertification;

    @Override
    public List<Certification> getHasCertificationList() {
        return hasCertification;
    }

    @Override
    public Certification getHasCertification() {
        return getFirst(hasCertification);
    }

    @Override
    public void addHasCertification(Certification hasCertification) {
        this.hasCertification = add(this.hasCertification, hasCertification);
    }

    private List<OfferCatalog> hasOfferCatalog;

    @Override
    public List<OfferCatalog> getHasOfferCatalogList() {
        return hasOfferCatalog;
    }

    @Override
    public OfferCatalog getHasOfferCatalog() {
        return getFirst(hasOfferCatalog);
    }

    @Override
    public void addHasOfferCatalog(OfferCatalog hasOfferCatalog) {
        this.hasOfferCatalog = add(this.hasOfferCatalog, hasOfferCatalog);
    }

    private List<OpeningHoursSpecification> hoursAvailable;

    @Override
    public List<OpeningHoursSpecification> getHoursAvailableList() {
        return hoursAvailable;
    }

    @Override
    public OpeningHoursSpecification getHoursAvailable() {
        return getFirst(hoursAvailable);
    }

    @Override
    public void addHoursAvailable(OpeningHoursSpecification hoursAvailable) {
        this.hoursAvailable = add(this.hoursAvailable, hoursAvailable);
    }

    @JsonLdFieldTypes({ URL.class, PropertyValue.class, Text.class })
    private List<Object> identifier;

    @Override
    public <T> List<T> getIdentifierList() {
        return (List<T>) identifier;
    }

    @Override
    public <T> T getIdentifier() {
        return (T) getFirst(identifier);
    }

    @Override
    public void addIdentifier(URL identifier) {
        this.identifier = add(this.identifier, identifier);
    }
    @Override
    public void addIdentifier(PropertyValue identifier) {
        this.identifier = add(this.identifier, identifier);
    }
    @Override
    public void addIdentifier(Text identifier) {
        this.identifier = add(this.identifier, identifier);
    }

    @JsonLdFieldTypes({ ImageObject.class, URL.class })
    private List<Object> image;

    @Override
    public <T> List<T> getImageList() {
        return (List<T>) image;
    }

    @Override
    public <T> T getImage() {
        return (T) getFirst(image);
    }

    @Override
    public void addImage(ImageObject image) {
        this.image = add(this.image, image);
    }
    @Override
    public void addImage(URL image) {
        this.image = add(this.image, image);
    }

    @JsonLdFieldTypes({ Service.class, Product.class })
    private List<Object> isRelatedTo;

    @Override
    public <T> List<T> getIsRelatedToList() {
        return (List<T>) isRelatedTo;
    }

    @Override
    public <T> T getIsRelatedTo() {
        return (T) getFirst(isRelatedTo);
    }

    @Override
    public void addIsRelatedTo(Service isRelatedTo) {
        this.isRelatedTo = add(this.isRelatedTo, isRelatedTo);
    }
    @Override
    public void addIsRelatedTo(Product isRelatedTo) {
        this.isRelatedTo = add(this.isRelatedTo, isRelatedTo);
    }

    @JsonLdFieldTypes({ Service.class, Product.class })
    private List<Object> isSimilarTo;

    @Override
    public <T> List<T> getIsSimilarToList() {
        return (List<T>) isSimilarTo;
    }

    @Override
    public <T> T getIsSimilarTo() {
        return (T) getFirst(isSimilarTo);
    }

    @Override
    public void addIsSimilarTo(Service isSimilarTo) {
        this.isSimilarTo = add(this.isSimilarTo, isSimilarTo);
    }
    @Override
    public void addIsSimilarTo(Product isSimilarTo) {
        this.isSimilarTo = add(this.isSimilarTo, isSimilarTo);
    }

    @JsonLdFieldTypes({ URL.class, ImageObject.class })
    private List<Object> logo;

    @Override
    public <T> List<T> getLogoList() {
        return (List<T>) logo;
    }

    @Override
    public <T> T getLogo() {
        return (T) getFirst(logo);
    }

    @Override
    public void addLogo(URL logo) {
        this.logo = add(this.logo, logo);
    }
    @Override
    public void addLogo(ImageObject logo) {
        this.logo = add(this.logo, logo);
    }

    @JsonLdFieldTypes({ CreativeWork.class, URL.class })
    private List<Object> mainEntityOfPage;

    @Override
    public <T> List<T> getMainEntityOfPageList() {
        return (List<T>) mainEntityOfPage;
    }

    @Override
    public <T> T getMainEntityOfPage() {
        return (T) getFirst(mainEntityOfPage);
    }

    @Override
    public void addMainEntityOfPage(CreativeWork mainEntityOfPage) {
        this.mainEntityOfPage = add(this.mainEntityOfPage, mainEntityOfPage);
    }
    @Override
    public void addMainEntityOfPage(URL mainEntityOfPage) {
        this.mainEntityOfPage = add(this.mainEntityOfPage, mainEntityOfPage);
    }

    private List<Text> name;

    @Override
    public List<Text> getNameList() {
        return name;
    }

    @Override
    public Text getName() {
        return getFirst(name);
    }

    @Override
    public void addName(Text name) {
        this.name = add(this.name, name);
    }

    @JsonLdFieldTypes({ Offer.class, Demand.class })
    private List<Object> offers;

    @Override
    public <T> List<T> getOffersList() {
        return (List<T>) offers;
    }

    @Override
    public <T> T getOffers() {
        return (T) getFirst(offers);
    }

    @Override
    public void addOffers(Offer offers) {
        this.offers = add(this.offers, offers);
    }
    @Override
    public void addOffers(Demand offers) {
        this.offers = add(this.offers, offers);
    }

    @JsonLdFieldTypes({ Person.class, Organization.class })
    private List<Object> owner;

    @Override
    public <T> List<T> getOwnerList() {
        return (List<T>) owner;
    }

    @Override
    public <T> T getOwner() {
        return (T) getFirst(owner);
    }

    @Override
    public void addOwner(Person owner) {
        this.owner = add(this.owner, owner);
    }
    @Override
    public void addOwner(Organization owner) {
        this.owner = add(this.owner, owner);
    }

    private List<Action> potentialAction;

    @Override
    public List<Action> getPotentialActionList() {
        return potentialAction;
    }

    @Override
    public Action getPotentialAction() {
        return getFirst(potentialAction);
    }

    @Override
    public void addPotentialAction(Action potentialAction) {
        this.potentialAction = add(this.potentialAction, potentialAction);
    }

    private List<Thing> produces;

    @Override
    public List<Thing> getProducesList() {
        return produces;
    }

    @Override
    public Thing getProduces() {
        return getFirst(produces);
    }

    @Override
    public void addProduces(Thing produces) {
        this.produces = add(this.produces, produces);
    }

    @JsonLdFieldTypes({ Person.class, Organization.class })
    private List<Object> provider;

    @Override
    public <T> List<T> getProviderList() {
        return (List<T>) provider;
    }

    @Override
    public <T> T getProvider() {
        return (T) getFirst(provider);
    }

    @Override
    public void addProvider(Person provider) {
        this.provider = add(this.provider, provider);
    }
    @Override
    public void addProvider(Organization provider) {
        this.provider = add(this.provider, provider);
    }

    private List<Text> providerMobility;

    @Override
    public List<Text> getProviderMobilityList() {
        return providerMobility;
    }

    @Override
    public Text getProviderMobility() {
        return getFirst(providerMobility);
    }

    @Override
    public void addProviderMobility(Text providerMobility) {
        this.providerMobility = add(this.providerMobility, providerMobility);
    }

    private List<Review> review;

    @Override
    public List<Review> getReviewList() {
        return review;
    }

    @Override
    public Review getReview() {
        return getFirst(review);
    }

    @Override
    public void addReview(Review review) {
        this.review = add(this.review, review);
    }

    private List<URL> sameAs;

    @Override
    public List<URL> getSameAsList() {
        return sameAs;
    }

    @Override
    public URL getSameAs() {
        return getFirst(sameAs);
    }

    @Override
    public void addSameAs(URL sameAs) {
        this.sameAs = add(this.sameAs, sameAs);
    }

    @JsonLdFieldTypes({ AdministrativeArea.class, GeoShape.class, Place.class })
    private List<Object> serviceArea;

    @Override
    public <T> List<T> getServiceAreaList() {
        return (List<T>) serviceArea;
    }

    @Override
    public <T> T getServiceArea() {
        return (T) getFirst(serviceArea);
    }

    @Override
    public void addServiceArea(AdministrativeArea serviceArea) {
        this.serviceArea = add(this.serviceArea, serviceArea);
    }
    @Override
    public void addServiceArea(GeoShape serviceArea) {
        this.serviceArea = add(this.serviceArea, serviceArea);
    }
    @Override
    public void addServiceArea(Place serviceArea) {
        this.serviceArea = add(this.serviceArea, serviceArea);
    }

    private List<Audience> serviceAudience;

    @Override
    public List<Audience> getServiceAudienceList() {
        return serviceAudience;
    }

    @Override
    public Audience getServiceAudience() {
        return getFirst(serviceAudience);
    }

    @Override
    public void addServiceAudience(Audience serviceAudience) {
        this.serviceAudience = add(this.serviceAudience, serviceAudience);
    }

    private List<Thing> serviceOutput;

    @Override
    public List<Thing> getServiceOutputList() {
        return serviceOutput;
    }

    @Override
    public Thing getServiceOutput() {
        return getFirst(serviceOutput);
    }

    @Override
    public void addServiceOutput(Thing serviceOutput) {
        this.serviceOutput = add(this.serviceOutput, serviceOutput);
    }

    @JsonLdFieldTypes({ Text.class, GovernmentBenefitsType.class })
    private List<Object> serviceType;

    @Override
    public <T> List<T> getServiceTypeList() {
        return (List<T>) serviceType;
    }

    @Override
    public <T> T getServiceType() {
        return (T) getFirst(serviceType);
    }

    @Override
    public void addServiceType(Text serviceType) {
        this.serviceType = add(this.serviceType, serviceType);
    }
    @Override
    public void addServiceType(GovernmentBenefitsType serviceType) {
        this.serviceType = add(this.serviceType, serviceType);
    }

    private List<Text> slogan;

    @Override
    public List<Text> getSloganList() {
        return slogan;
    }

    @Override
    public Text getSlogan() {
        return getFirst(slogan);
    }

    @Override
    public void addSlogan(Text slogan) {
        this.slogan = add(this.slogan, slogan);
    }

    @JsonLdFieldTypes({ Event.class, CreativeWork.class })
    private List<Object> subjectOf;

    @Override
    public <T> List<T> getSubjectOfList() {
        return (List<T>) subjectOf;
    }

    @Override
    public <T> T getSubjectOf() {
        return (T) getFirst(subjectOf);
    }

    @Override
    public void addSubjectOf(Event subjectOf) {
        this.subjectOf = add(this.subjectOf, subjectOf);
    }
    @Override
    public void addSubjectOf(CreativeWork subjectOf) {
        this.subjectOf = add(this.subjectOf, subjectOf);
    }

    @JsonLdFieldTypes({ URL.class, Text.class })
    private List<Object> termsOfService;

    @Override
    public <T> List<T> getTermsOfServiceList() {
        return (List<T>) termsOfService;
    }

    @Override
    public <T> T getTermsOfService() {
        return (T) getFirst(termsOfService);
    }

    @Override
    public void addTermsOfService(URL termsOfService) {
        this.termsOfService = add(this.termsOfService, termsOfService);
    }
    @Override
    public void addTermsOfService(Text termsOfService) {
        this.termsOfService = add(this.termsOfService, termsOfService);
    }

    private List<URL> url;

    @Override
    public List<URL> getUrlList() {
        return url;
    }

    @Override
    public URL getUrl() {
        return getFirst(url);
    }

    @Override
    public void addUrl(URL url) {
        this.url = add(this.url, url);
    }
}
