/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package org.schema.model.impl;

import com.weedow.schemaorg.commons.model.JsonLdFieldTypes;
import com.weedow.schemaorg.commons.model.JsonLdTypeName;
import java.util.List;
import org.schema.model.Action;
import org.schema.model.BedDetails;
import org.schema.model.BedType;
import org.schema.model.CreativeWork;
import org.schema.model.Event;
import org.schema.model.ImageObject;
import org.schema.model.Intangible;
import org.schema.model.Organization;
import org.schema.model.Person;
import org.schema.model.PropertyValue;
import org.schema.model.TextObject;
import org.schema.model.Thing;
import org.schema.model.datatype.Number;
import org.schema.model.datatype.Text;
import org.schema.model.datatype.URL;

/**
 * An entity holding detailed information about the available bed types, e.g. the quantity of twin beds for a hotel room. For the single case of just one bed of a certain type, you can use bed directly with a text. See also [[BedType]] (under development).
 *
 * @see <a href="https://schema.org/docs/collab/STI_Accommodation_Ontology">https://schema.org/docs/collab/STI_Accommodation_Ontology</a>
 * @see <a href="https://schema.org/BedDetails">https://schema.org/BedDetails</a>
 */
@JsonLdTypeName("BedDetails")
public class BedDetailsImpl extends com.weedow.schemaorg.commons.model.JsonLdNodeImpl implements BedDetails {

    @JsonLdFieldTypes({ URL.class, Text.class })
    private List<Object> additionalType;

    @Override
    public <T> List<T> getAdditionalTypeList() {
        return (List<T>) additionalType;
    }

    @Override
    public <T> T getAdditionalType() {
        return (T) getFirst(additionalType);
    }

    @Override
    public void addAdditionalType(URL additionalType) {
        this.additionalType = add(this.additionalType, additionalType);
    }
    @Override
    public void addAdditionalType(Text additionalType) {
        this.additionalType = add(this.additionalType, additionalType);
    }

    private List<Text> alternateName;

    @Override
    public List<Text> getAlternateNameList() {
        return alternateName;
    }

    @Override
    public Text getAlternateName() {
        return getFirst(alternateName);
    }

    @Override
    public void addAlternateName(Text alternateName) {
        this.alternateName = add(this.alternateName, alternateName);
    }

    @JsonLdFieldTypes({ TextObject.class, Text.class })
    private List<Object> description;

    @Override
    public <T> List<T> getDescriptionList() {
        return (List<T>) description;
    }

    @Override
    public <T> T getDescription() {
        return (T) getFirst(description);
    }

    @Override
    public void addDescription(TextObject description) {
        this.description = add(this.description, description);
    }
    @Override
    public void addDescription(Text description) {
        this.description = add(this.description, description);
    }

    private List<Text> disambiguatingDescription;

    @Override
    public List<Text> getDisambiguatingDescriptionList() {
        return disambiguatingDescription;
    }

    @Override
    public Text getDisambiguatingDescription() {
        return getFirst(disambiguatingDescription);
    }

    @Override
    public void addDisambiguatingDescription(Text disambiguatingDescription) {
        this.disambiguatingDescription = add(this.disambiguatingDescription, disambiguatingDescription);
    }

    @JsonLdFieldTypes({ URL.class, PropertyValue.class, Text.class })
    private List<Object> identifier;

    @Override
    public <T> List<T> getIdentifierList() {
        return (List<T>) identifier;
    }

    @Override
    public <T> T getIdentifier() {
        return (T) getFirst(identifier);
    }

    @Override
    public void addIdentifier(URL identifier) {
        this.identifier = add(this.identifier, identifier);
    }
    @Override
    public void addIdentifier(PropertyValue identifier) {
        this.identifier = add(this.identifier, identifier);
    }
    @Override
    public void addIdentifier(Text identifier) {
        this.identifier = add(this.identifier, identifier);
    }

    @JsonLdFieldTypes({ ImageObject.class, URL.class })
    private List<Object> image;

    @Override
    public <T> List<T> getImageList() {
        return (List<T>) image;
    }

    @Override
    public <T> T getImage() {
        return (T) getFirst(image);
    }

    @Override
    public void addImage(ImageObject image) {
        this.image = add(this.image, image);
    }
    @Override
    public void addImage(URL image) {
        this.image = add(this.image, image);
    }

    @JsonLdFieldTypes({ CreativeWork.class, URL.class })
    private List<Object> mainEntityOfPage;

    @Override
    public <T> List<T> getMainEntityOfPageList() {
        return (List<T>) mainEntityOfPage;
    }

    @Override
    public <T> T getMainEntityOfPage() {
        return (T) getFirst(mainEntityOfPage);
    }

    @Override
    public void addMainEntityOfPage(CreativeWork mainEntityOfPage) {
        this.mainEntityOfPage = add(this.mainEntityOfPage, mainEntityOfPage);
    }
    @Override
    public void addMainEntityOfPage(URL mainEntityOfPage) {
        this.mainEntityOfPage = add(this.mainEntityOfPage, mainEntityOfPage);
    }

    private List<Text> name;

    @Override
    public List<Text> getNameList() {
        return name;
    }

    @Override
    public Text getName() {
        return getFirst(name);
    }

    @Override
    public void addName(Text name) {
        this.name = add(this.name, name);
    }

    private List<Number> numberOfBeds;

    @Override
    public List<Number> getNumberOfBedsList() {
        return numberOfBeds;
    }

    @Override
    public Number getNumberOfBeds() {
        return getFirst(numberOfBeds);
    }

    @Override
    public void addNumberOfBeds(Number numberOfBeds) {
        this.numberOfBeds = add(this.numberOfBeds, numberOfBeds);
    }

    @JsonLdFieldTypes({ Person.class, Organization.class })
    private List<Object> owner;

    @Override
    public <T> List<T> getOwnerList() {
        return (List<T>) owner;
    }

    @Override
    public <T> T getOwner() {
        return (T) getFirst(owner);
    }

    @Override
    public void addOwner(Person owner) {
        this.owner = add(this.owner, owner);
    }
    @Override
    public void addOwner(Organization owner) {
        this.owner = add(this.owner, owner);
    }

    private List<Action> potentialAction;

    @Override
    public List<Action> getPotentialActionList() {
        return potentialAction;
    }

    @Override
    public Action getPotentialAction() {
        return getFirst(potentialAction);
    }

    @Override
    public void addPotentialAction(Action potentialAction) {
        this.potentialAction = add(this.potentialAction, potentialAction);
    }

    private List<URL> sameAs;

    @Override
    public List<URL> getSameAsList() {
        return sameAs;
    }

    @Override
    public URL getSameAs() {
        return getFirst(sameAs);
    }

    @Override
    public void addSameAs(URL sameAs) {
        this.sameAs = add(this.sameAs, sameAs);
    }

    @JsonLdFieldTypes({ Event.class, CreativeWork.class })
    private List<Object> subjectOf;

    @Override
    public <T> List<T> getSubjectOfList() {
        return (List<T>) subjectOf;
    }

    @Override
    public <T> T getSubjectOf() {
        return (T) getFirst(subjectOf);
    }

    @Override
    public void addSubjectOf(Event subjectOf) {
        this.subjectOf = add(this.subjectOf, subjectOf);
    }
    @Override
    public void addSubjectOf(CreativeWork subjectOf) {
        this.subjectOf = add(this.subjectOf, subjectOf);
    }

    @JsonLdFieldTypes({ Text.class, BedType.class })
    private List<Object> typeOfBed;

    @Override
    public <T> List<T> getTypeOfBedList() {
        return (List<T>) typeOfBed;
    }

    @Override
    public <T> T getTypeOfBed() {
        return (T) getFirst(typeOfBed);
    }

    @Override
    public void addTypeOfBed(Text typeOfBed) {
        this.typeOfBed = add(this.typeOfBed, typeOfBed);
    }
    @Override
    public void addTypeOfBed(BedType typeOfBed) {
        this.typeOfBed = add(this.typeOfBed, typeOfBed);
    }

    private List<URL> url;

    @Override
    public List<URL> getUrlList() {
        return url;
    }

    @Override
    public URL getUrl() {
        return getFirst(url);
    }

    @Override
    public void addUrl(URL url) {
        this.url = add(this.url, url);
    }
}
