/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package spec.model.impl;

import com.weedow.schemaorg.commons.model.JsonLdFieldTypes;
import com.weedow.schemaorg.commons.model.JsonLdTypeName;
import java.util.List;
import spec.model.Action;
import spec.model.CreativeWork;
import spec.model.DayOfWeek;
import spec.model.Event;
import spec.model.ImageObject;
import spec.model.Intangible;
import spec.model.OpeningHoursSpecification;
import spec.model.Organization;
import spec.model.Person;
import spec.model.PropertyValue;
import spec.model.QuantitativeValue;
import spec.model.ServicePeriod;
import spec.model.ShippingDeliveryTime;
import spec.model.StructuredValue;
import spec.model.TextObject;
import spec.model.Thing;
import spec.model.datatype.Text;
import spec.model.datatype.Time;
import spec.model.datatype.URL;

/**
 * ShippingDeliveryTime provides various pieces of information about delivery times for shipping.
 *
 * @see <a href="https://github.com/schemaorg/schemaorg/issues/2506">https://github.com/schemaorg/schemaorg/issues/2506</a>
 * @see <a href="https://schema.org/ShippingDeliveryTime">https://schema.org/ShippingDeliveryTime</a>
 */
@JsonLdTypeName("ShippingDeliveryTime")
public class ShippingDeliveryTimeImpl extends com.weedow.schemaorg.commons.model.JsonLdNodeImpl implements ShippingDeliveryTime {

    @JsonLdFieldTypes({ URL.class, Text.class })
    private List<Object> additionalType;

    @Override
    public <T> List<T> getAdditionalTypeList() {
        return (List<T>) additionalType;
    }

    @Override
    public <T> T getAdditionalType() {
        return (T) getFirst(additionalType);
    }

    @Override
    public void addAdditionalType(URL additionalType) {
        this.additionalType = add(this.additionalType, additionalType);
    }
    @Override
    public void addAdditionalType(Text additionalType) {
        this.additionalType = add(this.additionalType, additionalType);
    }

    private List<Text> alternateName;

    @Override
    public List<Text> getAlternateNameList() {
        return alternateName;
    }

    @Override
    public Text getAlternateName() {
        return getFirst(alternateName);
    }

    @Override
    public void addAlternateName(Text alternateName) {
        this.alternateName = add(this.alternateName, alternateName);
    }

    @JsonLdFieldTypes({ OpeningHoursSpecification.class, DayOfWeek.class })
    private List<Object> businessDays;

    @Override
    public <T> List<T> getBusinessDaysList() {
        return (List<T>) businessDays;
    }

    @Override
    public <T> T getBusinessDays() {
        return (T) getFirst(businessDays);
    }

    @Override
    public void addBusinessDays(OpeningHoursSpecification businessDays) {
        this.businessDays = add(this.businessDays, businessDays);
    }
    @Override
    public void addBusinessDays(DayOfWeek businessDays) {
        this.businessDays = add(this.businessDays, businessDays);
    }

    private List<Time> cutoffTime;

    @Override
    public List<Time> getCutoffTimeList() {
        return cutoffTime;
    }

    @Override
    public Time getCutoffTime() {
        return getFirst(cutoffTime);
    }

    @Override
    public void addCutoffTime(Time cutoffTime) {
        this.cutoffTime = add(this.cutoffTime, cutoffTime);
    }

    @JsonLdFieldTypes({ TextObject.class, Text.class })
    private List<Object> description;

    @Override
    public <T> List<T> getDescriptionList() {
        return (List<T>) description;
    }

    @Override
    public <T> T getDescription() {
        return (T) getFirst(description);
    }

    @Override
    public void addDescription(TextObject description) {
        this.description = add(this.description, description);
    }
    @Override
    public void addDescription(Text description) {
        this.description = add(this.description, description);
    }

    private List<Text> disambiguatingDescription;

    @Override
    public List<Text> getDisambiguatingDescriptionList() {
        return disambiguatingDescription;
    }

    @Override
    public Text getDisambiguatingDescription() {
        return getFirst(disambiguatingDescription);
    }

    @Override
    public void addDisambiguatingDescription(Text disambiguatingDescription) {
        this.disambiguatingDescription = add(this.disambiguatingDescription, disambiguatingDescription);
    }

    @JsonLdFieldTypes({ ServicePeriod.class, QuantitativeValue.class })
    private List<Object> handlingTime;

    @Override
    public <T> List<T> getHandlingTimeList() {
        return (List<T>) handlingTime;
    }

    @Override
    public <T> T getHandlingTime() {
        return (T) getFirst(handlingTime);
    }

    @Override
    public void addHandlingTime(ServicePeriod handlingTime) {
        this.handlingTime = add(this.handlingTime, handlingTime);
    }
    @Override
    public void addHandlingTime(QuantitativeValue handlingTime) {
        this.handlingTime = add(this.handlingTime, handlingTime);
    }

    @JsonLdFieldTypes({ URL.class, PropertyValue.class, Text.class })
    private List<Object> identifier;

    @Override
    public <T> List<T> getIdentifierList() {
        return (List<T>) identifier;
    }

    @Override
    public <T> T getIdentifier() {
        return (T) getFirst(identifier);
    }

    @Override
    public void addIdentifier(URL identifier) {
        this.identifier = add(this.identifier, identifier);
    }
    @Override
    public void addIdentifier(PropertyValue identifier) {
        this.identifier = add(this.identifier, identifier);
    }
    @Override
    public void addIdentifier(Text identifier) {
        this.identifier = add(this.identifier, identifier);
    }

    @JsonLdFieldTypes({ ImageObject.class, URL.class })
    private List<Object> image;

    @Override
    public <T> List<T> getImageList() {
        return (List<T>) image;
    }

    @Override
    public <T> T getImage() {
        return (T) getFirst(image);
    }

    @Override
    public void addImage(ImageObject image) {
        this.image = add(this.image, image);
    }
    @Override
    public void addImage(URL image) {
        this.image = add(this.image, image);
    }

    @JsonLdFieldTypes({ CreativeWork.class, URL.class })
    private List<Object> mainEntityOfPage;

    @Override
    public <T> List<T> getMainEntityOfPageList() {
        return (List<T>) mainEntityOfPage;
    }

    @Override
    public <T> T getMainEntityOfPage() {
        return (T) getFirst(mainEntityOfPage);
    }

    @Override
    public void addMainEntityOfPage(CreativeWork mainEntityOfPage) {
        this.mainEntityOfPage = add(this.mainEntityOfPage, mainEntityOfPage);
    }
    @Override
    public void addMainEntityOfPage(URL mainEntityOfPage) {
        this.mainEntityOfPage = add(this.mainEntityOfPage, mainEntityOfPage);
    }

    private List<Text> name;

    @Override
    public List<Text> getNameList() {
        return name;
    }

    @Override
    public Text getName() {
        return getFirst(name);
    }

    @Override
    public void addName(Text name) {
        this.name = add(this.name, name);
    }

    @JsonLdFieldTypes({ Person.class, Organization.class })
    private List<Object> owner;

    @Override
    public <T> List<T> getOwnerList() {
        return (List<T>) owner;
    }

    @Override
    public <T> T getOwner() {
        return (T) getFirst(owner);
    }

    @Override
    public void addOwner(Person owner) {
        this.owner = add(this.owner, owner);
    }
    @Override
    public void addOwner(Organization owner) {
        this.owner = add(this.owner, owner);
    }

    private List<Action> potentialAction;

    @Override
    public List<Action> getPotentialActionList() {
        return potentialAction;
    }

    @Override
    public Action getPotentialAction() {
        return getFirst(potentialAction);
    }

    @Override
    public void addPotentialAction(Action potentialAction) {
        this.potentialAction = add(this.potentialAction, potentialAction);
    }

    private List<URL> sameAs;

    @Override
    public List<URL> getSameAsList() {
        return sameAs;
    }

    @Override
    public URL getSameAs() {
        return getFirst(sameAs);
    }

    @Override
    public void addSameAs(URL sameAs) {
        this.sameAs = add(this.sameAs, sameAs);
    }

    @JsonLdFieldTypes({ Event.class, CreativeWork.class })
    private List<Object> subjectOf;

    @Override
    public <T> List<T> getSubjectOfList() {
        return (List<T>) subjectOf;
    }

    @Override
    public <T> T getSubjectOf() {
        return (T) getFirst(subjectOf);
    }

    @Override
    public void addSubjectOf(Event subjectOf) {
        this.subjectOf = add(this.subjectOf, subjectOf);
    }
    @Override
    public void addSubjectOf(CreativeWork subjectOf) {
        this.subjectOf = add(this.subjectOf, subjectOf);
    }

    @JsonLdFieldTypes({ ServicePeriod.class, QuantitativeValue.class })
    private List<Object> transitTime;

    @Override
    public <T> List<T> getTransitTimeList() {
        return (List<T>) transitTime;
    }

    @Override
    public <T> T getTransitTime() {
        return (T) getFirst(transitTime);
    }

    @Override
    public void addTransitTime(ServicePeriod transitTime) {
        this.transitTime = add(this.transitTime, transitTime);
    }
    @Override
    public void addTransitTime(QuantitativeValue transitTime) {
        this.transitTime = add(this.transitTime, transitTime);
    }

    private List<URL> url;

    @Override
    public List<URL> getUrlList() {
        return url;
    }

    @Override
    public URL getUrl() {
        return getFirst(url);
    }

    @Override
    public void addUrl(URL url) {
        this.url = add(this.url, url);
    }
}
