package com.weedow.maven.javadoc;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * Maven plugin to fix incomplete Javadoc in delomboked sources.
 * <p>
 * This plugin adds missing @return tags to getters and @param tags to setters
 * that were generated by Lombok but have incomplete or missing Javadoc.
 */
@Mojo(name = "fix-javadoc", defaultPhase = LifecyclePhase.GENERATE_SOURCES, threadSafe = true)
public class JavadocFixerMojo extends AbstractMojo {

    private static final String LOMBOK_ANNOTATIONS = "@java\\.lang\\.SuppressWarnings\\(\"all\"\\)\\s*@lombok\\.Generated\\s*";

    /**
     * Directory containing the delomboked Java sources.
     */
    @SuppressWarnings("unused")
    @Parameter(defaultValue = "${project.build.directory}/delombok", property = "sourceDirectory", required = true)
    private File sourceDirectory;

    /**
     * Skip the plugin execution.
     */
    @SuppressWarnings("unused")
    @Parameter(property = "javadoc.fixer.skip", defaultValue = "false")
    private boolean skip;

    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
        if (skip) {
            getLog().info("Skipping Javadoc fixer plugin execution");
            return;
        }

        if (!sourceDirectory.exists() || !sourceDirectory.isDirectory()) {
            getLog().warn("Source directory does not exist: " + sourceDirectory);
            return;
        }

        getLog().info("Fixing Javadoc in: " + sourceDirectory);

        try {
            List<Path> javaFiles = findJavaFiles(sourceDirectory.toPath());
            int filesProcessed = 0;
            int totalFixes = 0;

            for (Path javaFile : javaFiles) {
                int fixes = processFile(javaFile);
                if (fixes > 0) {
                    filesProcessed++;
                    totalFixes += fixes;
                }
            }

            getLog().info(String.format("Fixed %d Javadoc issues in %d files", totalFixes, filesProcessed));
        } catch (IOException e) {
            throw new MojoExecutionException("Error processing Java files", e);
        }
    }

    /**
     * Finds all Java files in the given directory recursively.
     */
    private List<Path> findJavaFiles(Path directory) throws IOException {
        List<Path> javaFiles = new ArrayList<>();
        try (Stream<Path> stream = Files.walk(directory)) {
            stream.filter(Files::isRegularFile)
                    .filter(path -> path.toString().endsWith(".java"))
                    .forEach(javaFiles::add);
        }
        return javaFiles;
    }

    /**
     * Processes a single Java file to fix Javadoc issues.
     * Returns the number of fixes applied.
     */
    private int processFile(Path file) throws IOException {
        String content = Files.readString(file, StandardCharsets.UTF_8);
        String originalContent = content;
        int fixCount = 0;

        // Fix default constructors without javadoc
        JavadocFix constructorFix = fixConstructorsWithoutJavadoc(content);
        content = constructorFix.content;
        fixCount += constructorFix.fixCount;

        // Fix canEqual methods without javadoc
        JavadocFix canEqualFix = fixCanEqualWithoutJavadoc(content);
        content = canEqualFix.content;
        fixCount += canEqualFix.fixCount;

        // Only write if changes were made
        if (!content.equals(originalContent)) {
            Files.writeString(file, content, StandardCharsets.UTF_8);
            getLog().debug("Fixed " + fixCount + " Javadoc issues in: " + file.getFileName());
        }

        return fixCount;
    }

    /** Fixes constructors without javadoc. */
    private JavadocFix fixConstructorsWithoutJavadoc(String content) {
        // Match default constructors with @java.lang.SuppressWarnings("all") and @lombok.Generated
        // Pattern matches: (indent)(@java.lang.SuppressWarnings("all")\n@lombok.Generated\n(public|protected) ClassName())
        Pattern pattern = Pattern.compile(
                "( *)(" + LOMBOK_ANNOTATIONS + "(public|protected) [A-Z]\\w*\\(\\))",
                Pattern.MULTILINE
        );

        Matcher matcher = pattern.matcher(content);
        StringBuilder result = new StringBuilder();
        int count = 0;

        while (matcher.find()) {
            String indent = matcher.group(1);
            String annotationsAndSignature = matcher.group(2);

            // Generate javadoc
            String javadoc = indent + "/** Default constructor */\n";

            matcher.appendReplacement(result,
                    Matcher.quoteReplacement(javadoc + annotationsAndSignature));
            count++;
        }
        matcher.appendTail(result);

        return new JavadocFix(result.toString(), count);
    }

    /** Fixes canEqual methods without javadoc. */
    private JavadocFix fixCanEqualWithoutJavadoc(String content) {
        // Match canEqual methods with @java.lang.SuppressWarnings("all") and @lombok.Generated
        // Pattern matches: (indent)(@java.lang.SuppressWarnings("all")\n@lombok.Generated\nprotected boolean canEqual(final java.lang.Object other))
        Pattern pattern = Pattern.compile(
                "( *)(" + LOMBOK_ANNOTATIONS + "protected boolean canEqual\\(final java\\.lang\\.Object other\\))",
                Pattern.MULTILINE
        );

        Matcher matcher = pattern.matcher(content);
        StringBuilder result = new StringBuilder();
        int count = 0;

        while (matcher.find()) {
            String indent = matcher.group(1);
            String annotationsAndSignature = matcher.group(2);

            // Generate javadoc
            String javadoc = indent + "/**\n" +
                    indent + " * canEqual method.\n" +
                    indent + " * @param other Other.\n" +
                    indent + " * @return true or false\n" +
                    indent + " */\n";

            matcher.appendReplacement(result,
                    Matcher.quoteReplacement(javadoc + annotationsAndSignature));
            count++;
        }
        matcher.appendTail(result);

        return new JavadocFix(result.toString(), count);
    }

    /**
     * Helper class to return both the modified content and the number of fixes applied.
     */
    private record JavadocFix(String content, int fixCount) {
    }
}
