/*
 * This class is auto generated by the schema.org code generator program.
 * https://github.com/Kobee1203/schema-org-java
 * Do not edit the class manually.
 */
package filters.model.impl;

import com.weedow.schemaorg.commons.model.JsonLdFieldTypes;
import com.weedow.schemaorg.commons.model.JsonLdTypeName;
import filters.model.ContactPoint;
import filters.model.CreativeWork;
import filters.model.HealthInsurancePlan;
import filters.model.HealthPlanFormulary;
import filters.model.HealthPlanNetwork;
import filters.model.ImageObject;
import filters.model.Intangible;
import filters.model.Organization;
import filters.model.Person;
import filters.model.PropertyValue;
import filters.model.TextObject;
import filters.model.Thing;
import filters.model.datatype.Text;
import filters.model.datatype.URL;
import java.util.List;

/**
 * A US-style health insurance plan, including PPOs, EPOs, and HMOs.
 *
 * @see <a href="https://pending.schema.org">https://pending.schema.org</a>
 * @see <a href="https://github.com/schemaorg/schemaorg/issues/1062">https://github.com/schemaorg/schemaorg/issues/1062</a>
 * @see <a href="https://schema.org/HealthInsurancePlan">https://schema.org/HealthInsurancePlan</a>
 */
@JsonLdTypeName("HealthInsurancePlan")
public class HealthInsurancePlanImpl extends com.weedow.schemaorg.commons.model.JsonLdNodeImpl implements HealthInsurancePlan {

    private List<URL> benefitsSummaryUrl;

    @Override
    public List<URL> getBenefitsSummaryUrlList() {
        return benefitsSummaryUrl;
    }

    @Override
    public URL getBenefitsSummaryUrl() {
        return getFirst(benefitsSummaryUrl);
    }

    @Override
    public void addBenefitsSummaryUrl(URL benefitsSummaryUrl) {
        this.benefitsSummaryUrl = add(this.benefitsSummaryUrl, benefitsSummaryUrl);
    }

    private List<ContactPoint> contactPoint;

    @Override
    public List<ContactPoint> getContactPointList() {
        return contactPoint;
    }

    @Override
    public ContactPoint getContactPoint() {
        return getFirst(contactPoint);
    }

    @Override
    public void addContactPoint(ContactPoint contactPoint) {
        this.contactPoint = add(this.contactPoint, contactPoint);
    }

    @JsonLdFieldTypes({ TextObject.class, Text.class })
    private List<Object> description;

    @Override
    public <T> List<T> getDescriptionList() {
        return (List<T>) description;
    }

    @Override
    public <T> T getDescription() {
        return (T) getFirst(description);
    }

    @Override
    public void addDescription(TextObject description) {
        this.description = add(this.description, description);
    }
    @Override
    public void addDescription(Text description) {
        this.description = add(this.description, description);
    }

    private List<Text> disambiguatingDescription;

    @Override
    public List<Text> getDisambiguatingDescriptionList() {
        return disambiguatingDescription;
    }

    @Override
    public Text getDisambiguatingDescription() {
        return getFirst(disambiguatingDescription);
    }

    @Override
    public void addDisambiguatingDescription(Text disambiguatingDescription) {
        this.disambiguatingDescription = add(this.disambiguatingDescription, disambiguatingDescription);
    }

    private List<Text> healthPlanDrugOption;

    @Override
    public List<Text> getHealthPlanDrugOptionList() {
        return healthPlanDrugOption;
    }

    @Override
    public Text getHealthPlanDrugOption() {
        return getFirst(healthPlanDrugOption);
    }

    @Override
    public void addHealthPlanDrugOption(Text healthPlanDrugOption) {
        this.healthPlanDrugOption = add(this.healthPlanDrugOption, healthPlanDrugOption);
    }

    private List<Text> healthPlanDrugTier;

    @Override
    public List<Text> getHealthPlanDrugTierList() {
        return healthPlanDrugTier;
    }

    @Override
    public Text getHealthPlanDrugTier() {
        return getFirst(healthPlanDrugTier);
    }

    @Override
    public void addHealthPlanDrugTier(Text healthPlanDrugTier) {
        this.healthPlanDrugTier = add(this.healthPlanDrugTier, healthPlanDrugTier);
    }

    private List<Text> healthPlanId;

    @Override
    public List<Text> getHealthPlanIdList() {
        return healthPlanId;
    }

    @Override
    public Text getHealthPlanId() {
        return getFirst(healthPlanId);
    }

    @Override
    public void addHealthPlanId(Text healthPlanId) {
        this.healthPlanId = add(this.healthPlanId, healthPlanId);
    }

    private List<URL> healthPlanMarketingUrl;

    @Override
    public List<URL> getHealthPlanMarketingUrlList() {
        return healthPlanMarketingUrl;
    }

    @Override
    public URL getHealthPlanMarketingUrl() {
        return getFirst(healthPlanMarketingUrl);
    }

    @Override
    public void addHealthPlanMarketingUrl(URL healthPlanMarketingUrl) {
        this.healthPlanMarketingUrl = add(this.healthPlanMarketingUrl, healthPlanMarketingUrl);
    }

    @JsonLdFieldTypes({ URL.class, PropertyValue.class, Text.class })
    private List<Object> identifier;

    @Override
    public <T> List<T> getIdentifierList() {
        return (List<T>) identifier;
    }

    @Override
    public <T> T getIdentifier() {
        return (T) getFirst(identifier);
    }

    @Override
    public void addIdentifier(URL identifier) {
        this.identifier = add(this.identifier, identifier);
    }
    @Override
    public void addIdentifier(PropertyValue identifier) {
        this.identifier = add(this.identifier, identifier);
    }
    @Override
    public void addIdentifier(Text identifier) {
        this.identifier = add(this.identifier, identifier);
    }

    @JsonLdFieldTypes({ ImageObject.class, URL.class })
    private List<Object> image;

    @Override
    public <T> List<T> getImageList() {
        return (List<T>) image;
    }

    @Override
    public <T> T getImage() {
        return (T) getFirst(image);
    }

    @Override
    public void addImage(ImageObject image) {
        this.image = add(this.image, image);
    }
    @Override
    public void addImage(URL image) {
        this.image = add(this.image, image);
    }

    private List<HealthPlanFormulary> includesHealthPlanFormulary;

    @Override
    public List<HealthPlanFormulary> getIncludesHealthPlanFormularyList() {
        return includesHealthPlanFormulary;
    }

    @Override
    public HealthPlanFormulary getIncludesHealthPlanFormulary() {
        return getFirst(includesHealthPlanFormulary);
    }

    @Override
    public void addIncludesHealthPlanFormulary(HealthPlanFormulary includesHealthPlanFormulary) {
        this.includesHealthPlanFormulary = add(this.includesHealthPlanFormulary, includesHealthPlanFormulary);
    }

    private List<HealthPlanNetwork> includesHealthPlanNetwork;

    @Override
    public List<HealthPlanNetwork> getIncludesHealthPlanNetworkList() {
        return includesHealthPlanNetwork;
    }

    @Override
    public HealthPlanNetwork getIncludesHealthPlanNetwork() {
        return getFirst(includesHealthPlanNetwork);
    }

    @Override
    public void addIncludesHealthPlanNetwork(HealthPlanNetwork includesHealthPlanNetwork) {
        this.includesHealthPlanNetwork = add(this.includesHealthPlanNetwork, includesHealthPlanNetwork);
    }

    @JsonLdFieldTypes({ CreativeWork.class, URL.class })
    private List<Object> mainEntityOfPage;

    @Override
    public <T> List<T> getMainEntityOfPageList() {
        return (List<T>) mainEntityOfPage;
    }

    @Override
    public <T> T getMainEntityOfPage() {
        return (T) getFirst(mainEntityOfPage);
    }

    @Override
    public void addMainEntityOfPage(CreativeWork mainEntityOfPage) {
        this.mainEntityOfPage = add(this.mainEntityOfPage, mainEntityOfPage);
    }
    @Override
    public void addMainEntityOfPage(URL mainEntityOfPage) {
        this.mainEntityOfPage = add(this.mainEntityOfPage, mainEntityOfPage);
    }

    private List<Text> name;

    @Override
    public List<Text> getNameList() {
        return name;
    }

    @Override
    public Text getName() {
        return getFirst(name);
    }

    @Override
    public void addName(Text name) {
        this.name = add(this.name, name);
    }

    @JsonLdFieldTypes({ Person.class, Organization.class })
    private List<Object> owner;

    @Override
    public <T> List<T> getOwnerList() {
        return (List<T>) owner;
    }

    @Override
    public <T> T getOwner() {
        return (T) getFirst(owner);
    }

    @Override
    public void addOwner(Person owner) {
        this.owner = add(this.owner, owner);
    }
    @Override
    public void addOwner(Organization owner) {
        this.owner = add(this.owner, owner);
    }

    private List<URL> url;

    @Override
    public List<URL> getUrlList() {
        return url;
    }

    @Override
    public URL getUrl() {
        return getFirst(url);
    }

    @Override
    public void addUrl(URL url) {
        this.url = add(this.url, url);
    }

    @JsonLdFieldTypes({ URL.class, Text.class })
    private List<Object> usesHealthPlanIdStandard;

    @Override
    public <T> List<T> getUsesHealthPlanIdStandardList() {
        return (List<T>) usesHealthPlanIdStandard;
    }

    @Override
    public <T> T getUsesHealthPlanIdStandard() {
        return (T) getFirst(usesHealthPlanIdStandard);
    }

    @Override
    public void addUsesHealthPlanIdStandard(URL usesHealthPlanIdStandard) {
        this.usesHealthPlanIdStandard = add(this.usesHealthPlanIdStandard, usesHealthPlanIdStandard);
    }
    @Override
    public void addUsesHealthPlanIdStandard(Text usesHealthPlanIdStandard) {
        this.usesHealthPlanIdStandard = add(this.usesHealthPlanIdStandard, usesHealthPlanIdStandard);
    }
}
