name: Dependabot Workflow

on: [ pull_request ]

jobs:
  build:
    if: ${{ github.actor == 'dependabot[bot]' }}

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v3
        env:
          GIT_TRACE: 1
          GIT_CURL_VERBOSE: 1
        with:
          ref: ${{ github.REF }}

      - name: Retrieve entire repository history
        run: |
          git fetch --prune --unshallow

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Maven Version
        run: mvn --version

      - name: Build Project And Analyze with Sonar
        run: mvn -e -B -U clean install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
