name: Deployment

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    runs-on: ubuntu-latest

    steps:
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: List keys
        run: gpg -K

      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v6
        env:
          GIT_TRACE: 1
          GIT_CURL_VERBOSE: 1
        with:
          ref: ${{ github.REF }}

      - name: Set up JDK 17 and Maven Central Repository configuration
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_TOKEN

      - name: Maven Version
        run: mvn --version

      - name: Build and Deploy to the Maven Central Repository
        run: mvn -B -U clean deploy -DskipTests -P central
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}